language: android
dist: trusty
sudo: required
licenses:
  - '.+'
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
jdk:
  - oraclejdk8
before_install:
  - chmod +x ./SOURCE/gradlew
before_script:
  # Create and start emulator
  - android list targets
script:
  - ./SOURCE/gradlew build connectedCheck --stacktrace
  #- ./SOURCE/gradlew assembleDebug assembleRelease testDebug

notifications:
  email:
    recipients:
      - aquarius.superstar@gmail.com
      - thinhnguyenkim155@gmail.com
      - phanquankrb@gmail.com
      - tanhaha123.mail@gmail.com
      - ntquyen98@gmail.com
      - hophongit98@gmail.com
    on_success: always
    on_failure: always