language: android
dist: trusty
sudo: required
licenses:
  - '.+'
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
jdk:
  - oraclejdk8
before_install:
  - chmod +x ./SOURCE/gradlew
before_script:
  # Create and start emulator
  - android list targets
script:
  - ./SOURCE/gradlew tasks --info
  - ./SOURCE/gradlew build connectedCheck #--stacktrace
  #- ./SOURCE/gradlew assembleDebug assembleRelease testDebug

notifications:
  email: true
    on_success: always
    on_failure: always