language: android
dist: trusty
sudo: required
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
before_script:
  # Create and start emulator
  - android list targets
  - chmod +x ./SOURCE/gradlew
script:
  - ./SOURCE/gradlew build --stacktrace